services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbnode
    ports:
      - "5432:5432"
    networks:
      - libr_network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    # command: Fresh
    # delevop:
    #   watch:
    #     - action: sync
    #     - path: .
    #     - ignore: tmp/
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=dbnode
      - DB_SSLMODE=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - libr_network

networks:
  libr_network:
    driver: bridge